// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://duyxbtfknilgrvgsvlyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1eXhidGZrbmlsZ3J2Z3N2bHl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMzI5NzIsImV4cCI6MjA2MzYwODk3Mn0.zzHn2JJHLnZn-WD97J9y0EJkRw7nfJlj6ZyPVWDVJHI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);